### ISSUE TITLE
System down

### ISSUE THREAD

**Issue by AhmadHakami** [evanhu1/talk2arxiv#4]
I'm attempting to use your server with my `OpenAI API` code but it's not functioning

Even when I try it with different papers I added `talk2` before the arXiv paper link Like _(talk2 + arxiv.org/pdf/2311.12454.pdf)_ and everything worked well in the GUI page and embedding the document was successful but all the sent questions result in the same error message `Embedding server is down Please try again later`

what could be the issue

**Comment by claudioantonio** [comment]
Same here.

**Comment by evanhu1** [comment]
Usually when I've encountered "Embedding server is down Please try again later" it's because the PDF is being processed for the first time (not previously seen and so not cached), which means the embeddings generated from it need time to propagate to the embedding database. Does the error persist after waiting a few minutes?

**Comment by claudioantonio** [comment]
> Usually when I've encountered "Embedding server is down Please try again later" it's because the PDF is being processed for the first time (not previously seen and so not cached), which means the embeddings generated from it need time to propagate to the embedding database. Does the error persist after waiting a few minutes?

Yes, it persists... 😔 
I am trying with the following paper: https://www.talk2arxiv.org/pdf/2212.12439.pdf

**Comment by claudioantonio** [comment]
This is what google chrome inspect shows when I load the page with the PDF above.
![image](https://github.com/evanhu1/talk2arxiv/assets/12503122/17a5edd5-982e-43e0-9da6-b1521bca88f2)

**Comment by evanhu1** [comment]
It should be fixed now. Thanks for alerting me to this, the free tier of Pinecone DB had filled up. I've switched the system to use the open-source Qdrant now!

**Comment by claudioantonio** [comment]
Thansk a lot!!!

**Comment by mfouesneau** [comment]
Down again.
