### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by dengjuan0721** [evanhu1/talk2arxiv#5]
> ⨯ app/pdf/[paper_id]/page.tsx (10:16) @ window
 ⨯ ReferenceError: window is not defined
    at Page (./app/pdf/[paper_id]/page.tsx:19:19)
   8 |   const messageFormRef = useRef<HTMLDivElement>(null);
   9 |   const resizeRef = useRef(false);
 >10 |   const width = window.innerWidth
     |                ^
  11 |   const paper_id = params.paper_id;
  12 |
  13 |   const handleMouseDown = useCallback(() => {

after i visit the http://localhost:3000/, terminal shows message above. 
some of the pdfs can be read and interacted with, but other can't.

**Comment by evanhu1** [comment]
The vector db was full. This ReferenceError is actually innocuous. Should be fixed now!
